name: Build API

on:
  push:
    branches: [ "main" ]
    paths:
      - "data/**"
      - "schema/**"
      - "test/**"
      - "build.mjs"
      - "package.json"
      - "package-lock.json"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install
        run: npm ci || npm install

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Commit API data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Build API data." || echo "No changes to commit."
          git push
